# Use an official Python runtime as a parent image
FROM python:3.10.0

# Set the working directory in the container
WORKDIR /client

# Copy the current directory contents into the container at /app
COPY . /client/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 9999

# Define environment variable
ENV NAME SmartTraid
ENV IP = 0
ENV PORT = 9999

# Run app.py when the container launches
CMD ["python", "loging_page.py"]
