# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file and install Python dependencies
COPY . . 
COPY /crts/ /app
COPY ./requairments.txt /app/requairments.txt
# COPY ./client/requirements.txt /app/requirements.txt
RUN pip install --upgrade pip 
RUN pip install --no-cache-dir -r requairments.txt

# Copy the rest of your app's source code from your host to your image filesystem.

# Expose the port Streamlit runs on
EXPOSE 8501

# Command to run on container start
CMD ["streamlit", "run", "loging_page.py"]
