version: '3.8'

services:
  db:
    image: mongo:4.4
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: te13@t$3t
      MONGO_INITDB_DATABASE: SmartTraid
    volumes:
      - mongodb_data:/data/db
    networks:
      SmartTraid:
        ipv4_address: 172.18.0.2
    ports:
      - '27017:27017'
      
  server:
    container_name: server
    links:
      - db
    depends_on:
      - db
    build:
      context: ./server
      dockerfile: Dockerfile.server
    # healthcheck:
      # test: ['CMD-SHELL', "echo | openssl s_client -connect 172.18.0.3:3000 -servername localhost -CAfile /certs/server.crt.pem -verify_return_error -brief || exit 1"]
      # interval: 10s
      # timeout: 5s
      # retries: 5
    ports:
      - '3000:3000'
    volumes:
      - certs:/certs
    networks:
      SmartTraid:
        ipv4_address: 172.18.0.3

  client:
    container_name: client
    links:
      - server
    # depends_on:
      # server:
        # condition: service_healthy
    build: 
      context: ./client
      dockerfile: Dockerfile.client
    healthcheck:
      test: ['CMD-SHELL', "curl -f client://client:8501 --cacert /certs/server.crt.pem || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      SmartTraid:
        ipv4_address: 172.18.0.4  # Corrected IP address
    ports:
      - '8501:8501'
    volumes:
      - certs:/certs

volumes:
  mongodb_data:
    driver: local
  certs:
    driver: local
networks:
  SmartTraid:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16 
  