# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY requairments.txt /app/requairments.txt
COPY /crts /app/crts
# COPY server/requairments.txt /app/requairments.txt


# Install any needed packages specified in requirements.txt
RUN pip install --upgrade pip   
RUN pip install --no-cache-dir -r requairments.txt

COPY . .
# Make port 3000 available to the world outside this container
EXPOSE 3000

# Define environment variables
ENV DB_HOST=db \
    DB_PORT=27017 \
    DB_USER=root \
    DB_PASSWORD=te13@t$3t \
    DB_NAME=SmartTraidserver \
    SENDER_EMAIL=youremail@gmail.com \
    SENDER_PASSWORD=yourpassword \
    FILE_SYSTEM=False \
    EXCHANGE_API_KEY=85dce83d89dc8448c7bd4130

# Run server.py when the container launches
CMD ["python", "server.py", "9999", "--crt=crts/server.csr", "--key=crts/server.key"]
